### ISSUE TITLE
Whitelists at http level (MainRule) not work

### ISSUE THREAD

**Issue by houjq3** [nbs-system/naxsi#464] opened 2019-04-01 07:44 UTC
eg："BasicRule wl:1013;" which is present at location level can work nomal. But "MainRule wl:1013;"  which is present at http level cannot work. Why?

**Comment by diadal** [comment] 2019-04-08 13:38
am facing same issue how to white list where is the sample of BasicRule config file thanks

**Comment by buixor** [comment] 2019-05-07 07:23
Because naxsi [BasicRule configuration is per location](https://github.com/nbs-system/naxsi/wiki/rules-bnf)

**Comment by rhubard** [comment] 2019-05-07 07:31
"Rules can be present at location level (BasicRule) or at http level (MainRule)."
This is the original words of the document，My question is why “MainRule” does not work at http level?

**Comment by buixor** [comment] 2019-05-07 09:50
> My question is why “MainRule” does not work at http level?

`MainRule` should work at http level, and is part of unit tests.

Can you provide a configuration where it doesn't work so I can try to reproduce it ?

**Comment by rhubard** [comment] 2019-05-08 01:25
```nginx
http {
    include mime.types;
	default_type application/octet-stream;
	
	include naxsi_core.rules;
	MainRule wl:1000;
	
	server {
		listen 41100 default_server;
		listen [::]:41100 default_server;
		server_name _;
		location / {
			SecRulesEnabled;
			DeniedUrl "/RequestDenied";
			CheckRule "$SQL >= 4" BLOCK;
			root html;
			index index.html;
		}
		location /RequestDenied {
			return 403;
		}
	}
}
```

I configured "MainRule wl:1000;", which means that "sql keyword" is whitelisted. However, when I visit "http://xx/insert", I will be intercepted by naxsi.

**Comment by diadal** [comment] 2019-05-08 09:55
where will I paste this code `MainRule id:4242 str:z "mz:$ARGS_VAR:X|BODY";`

please can you send full sample of your nginx config file

**Comment by rhubard** [comment] 2019-05-08 10:16
> where will I paste this code `MainRule id:4242 str:z "mz:$ARGS_VAR:X|BODY";`
> 
> please can you send full sample of your nginx config file

Such as my above configuration “MainRule wl:1000;”，Please open a new issue yourself, my own feedback has not been resolved.Thanks!

**Comment by rhubard** [comment] 2019-05-10 09:37
> > My question is why “MainRule” does not work at http level?
> 
> `MainRule` should work at http level, and is part of unit tests.
> 
> Can you provide a configuration where it doesn't work so I can try to reproduce it ?

```nginx
http {
    include mime.types;
    default_type application/octet-stream;

    include naxsi_core.rules;
    MainRule wl:1000;

    server {
        listen 41100 default_server;
        listen [::]:41100 default_server;
        server_name _;
        location / {
            SecRulesEnabled;
            DeniedUrl "/RequestDenied";
            CheckRule "$SQL >= 4" BLOCK;
            root html;
            index index.html;
        }
        location /RequestDenied {
            return 403;
        }
    }
}
```

I configured "MainRule wl:1000;", which means that "sql keyword" is whitelisted. However, when I visit "http://xx/insert", I will be intercepted by naxsi.

**Comment by Napsty** [comment] 2020-05-05 13:22
If I understand the documentation correctly you cannot run a MainRule to whitelist another MainRule. You need to use a BasicRule for this. And BasicRule is to be defined in the location context. 
Someone correct me if I misunderstood this.

**Comment by rhubard** [comment] 2020-05-07 00:24
> If I understand the documentation correctly you cannot run a MainRule to whitelist another MainRule. You need to use a BasicRule for this. And BasicRule is to be defined in the location context.
> Someone correct me if I misunderstood this.

Yeah, from the test results, this is indeed the case. I think the document should explain that the mainRule whitelist does not work.

**Closed** 2023-11-08 09:28 UTC
Labels: documentation, question
