### ISSUE TITLE
PCRE2 problems

### ISSUE THREAD

**Issue by eilandert** [nbs-system/naxsi#600] opened 2022-07-07 14:13 UTC
Referring to https://github.com/nbs-system/naxsi/issues/593

temporarily workaround:

git clone https://github.com/nbs-system/naxsi.git
cd naxsi
git reset --hard 304e66d86fc4771821585b1bc32169de8afc9cea
wget https://patch-diff.githubusercontent.com/raw/nbs-system/naxsi/pull/598.patch
patch -p1 < 598.patch (1 hunk fails but that's no problem, it tries to replace a line with the same line)

And start building nginx with --with-pcre --without-pcre2

Basicly, clone this repo, go back to before the PCRE2 PR (it prevents building as pcre), apply the patch for the new 1.23.0 api and build NGINX with PCRE instead of PCRE2

tester: @tim-snapt

**Comment by wargio** [comment] 2022-07-07 14:46
the issue is that this is not a patch, is a workaround.

**Comment by wargio** [comment] 2022-07-15 00:12
closing since this issue has been fixed here: https://github.com/wargio/naxsi

**Closed by wargio** 2022-07-15 00:12 UTC
