### ISSUE TITLE
GPG key id 251A28DE2685AED from the installation guide isn't valid

### ISSUE THREAD

**Issue by jsdream** [nbs-system/naxsi#490] opened 2020-01-28 10:28 UTC
I'm following the installation guide (https://github.com/nbs-system/naxsi/wiki/naxsi-compile) and stuck at verifying the signature.
`gpg --recv-key 251A28DE2685AED` gives me `gpg: "251A28DE2685AED" not a key ID: skipping`

Is the key ID wrong or it's me doing something wrong?

**Comment by wargio** [comment] 2020-01-28 17:09
for some reason that key is not available anymore on the keyserver.
i'll try tomorrow to find which key that is linked to and re-upload the pubkey

**Comment by jsdream** [comment] 2020-01-29 07:53
@wargio Thank you for your quick reply. Looking forward to it.

**Comment by wargio** [comment] 2020-01-29 09:54
the issue is that was missing a `4` at the end. i've updated the wiki.
the key that you have to fetch is `251A28DE2685AED4` so just `gpg --recv-key 251A28DE2685AED4` and should work

**Comment by jsdream** [comment] 2020-01-29 10:09
Thanks @wargio. Now the key is being fetched, but I'm getting another error when trying to verify:
```gpg: key 251A28DE2685AED4: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
gpg: assuming signed data in 'naxsi-0.56.tar.gz'
gpg: Signature made Wed Jun 27 10:38:00 2018 UTC
gpg:                using RSA key 5FA35473CA73872AA9731F5C251A28DE2685AED4
gpg:                issuer "tko@nbs-system.com"
gpg: Can't check signature: No public key
```

**Comment by wargio** [comment] 2020-01-29 10:28
> Thanks @wargio. Now the key is being fetched, but I'm getting another error when trying to verify:
> 
> ```
> gpg: Total number processed: 1
> gpg:           w/o user IDs: 1
> gpg: assuming signed data in 'naxsi-0.56.tar.gz'
> gpg: Signature made Wed Jun 27 10:38:00 2018 UTC
> gpg:                using RSA key 5FA35473CA73872AA9731F5C251A28DE2685AED4
> gpg:                issuer "tko@nbs-system.com"
> gpg: Can't check signature: No public key
> ```

i think something went wrong when fetching the key.

this is what it should look like:
```
$ gpg --recv-key 251A28DE2685AED4
gpg: enabled debug flags: memstat
gpg: key 251A28DE2685AED4: public key "Naxsi Project (Key Used To Sign Code) <tko@nbs-system.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keydb: handles=3 locks=2 parse=2 get=2
gpg:        build=1 update=0 insert=1 delete=0
gpg:        reset=1 found=2 not=2 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=6 cached=4 good=4 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/32768 bytes in 0 blocks


$ gpg --verify naxsi-0.56.zip.asc 
gpg: enabled debug flags: memstat
gpg: assuming signed data in 'naxsi-0.56.zip'
gpg: Signature made Wed 27 Jun 2018 12:38:13 PM CEST
gpg:                using RSA key 5FA35473CA73872AA9731F5C251A28DE2685AED4
gpg:                issuer "tko@nbs-system.com"
gpg: Good signature from "Naxsi Project (Key Used To Sign Code) <tko@nbs-system.com>" [full]
gpg: keydb: handles=3 locks=0 parse=3 get=3
gpg:        build=0 update=0 insert=0 delete=0
gpg:        reset=0 found=3 not=0 cache=0 not=0
gpg: kid_not_found_cache: count=0 peak=0 flushes=0
gpg: sig_cache: total=6 cached=6 good=6 bad=0
gpg: random usage: poolsize=600 mixed=0 polls=0/0 added=0/0
              outmix=0 getlvl1=0/0 getlvl2=0/0
gpg: rndjent stat: collector=0x0000000000000000 calls=0 bytes=0
gpg: secmem usage: 0/32768 bytes in 0 blocks
```

**Comment by jsdream** [comment] 2020-01-29 10:35
@wargio The issue was my end. I'm running this inside Docker container based on Nginx official image and looks like it was fetching the key from a wrong keyserver. Adding `--keyserver keyserver.ubuntu.com` fixed the problem.

**Comment by wargio** [comment] 2020-01-29 10:37
ok. i'm closing the issue then, since it's solved.
:)

**Closed by wargio** 2020-01-29 10:37 UTC
