### ISSUE TITLE
gcc 11 build failed

### ISSUE THREAD

**Issue by vndroid** [nbs-system/naxsi#594] opened 2022-05-29 06:22 UTC
### Environment

- Alpine:3.16
- gcc 11

### Error

```
/src/naxsi/naxsi_src/naxsi_runtime.c: In function 'ngx_http_process_basic_rule_buffer':
/src/naxsi/naxsi_src/naxsi_runtime.c:205:61: error: invalid use of incomplete typedef 'ngx_regex_t' {aka 'struct pcre2_real_code_8'}
  205 |       (tmp_idx < len && (match = pcre_exec(rl->br->rx->regex->code,
      |                                                             ^~
/src/naxsi/naxsi_src/naxsi_runtime.c: In function 'ngx_http_naxsi_pcre_wrapper':
/src/naxsi/naxsi_src/naxsi_runtime.c:500:30: error: invalid use of incomplete typedef 'ngx_regex_t' {aka 'struct pcre2_real_code_8'}
  500 |   match = pcre_exec(rx->regex->code, 0, (const char*)str, len, 0, 0, captures, 1);
      |                              ^~
make[1]: *** [objs/Makefile:3170: objs/addon/naxsi_src/naxsi_runtime.o] Error 1
make[1]: Leaving directory '/src/nginx-quic'
make: *** [Makefile:16: modules] Error 2

```

**Comment by grazzolini** [comment] 2022-06-10 13:13
I'm having this exact same issue on Arch.

**Comment by wargio** [comment] 2022-06-10 13:22
which version of nginx is this?

**Comment by grazzolini** [comment] 2022-06-10 13:25
Latest stable, 1.22.0.

**Comment by heftig** [comment] 2022-06-10 13:28
Duplicate of https://github.com/nbs-system/naxsi/issues/580

**Comment by wargio** [comment] 2022-06-10 13:39
ok closing this for the other one.

**Closed** 2022-07-15 00:14 UTC
